import type { Metadata } from "next";
import "./globals.css";
import {Outfit} from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

export const metadata: Metadata = {
  title: "Blog Website - Vodea Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        {children}
        <Toaster
          position="bottom-right"
          richColors
          toastOptions={{
            duration: 3000,
            className: "bg-gray-800 text-white",
          }}
        />
      </body>
    </html>
  );
}
